trigger:
  - '*'

variables:
  b: "Hello" 

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job:
  variables:
    a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
    b: $[format('Hello {0} {1}', 'John', 'Doe')]
    c: $[format('{0:yyyyMMdd}', pipeline.startTime)]
   # d: $[format(12, "X4")]
    e: $[format(.2468013, "P")]
    

  steps:
    - bash: echo $(a)
    - bash: echo $(b)
    - bash: echo $(c)
  #  - bash: echo $(d)
    - bash: echo $(e)
    