trigger:
- '*'
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

steps: 
  - script: echo hello world
  - script: echo $(name)
  #- script: echo $[format('{0:00}', variables.MyBuildNumber)]


# stages:

# - stage: test
#   jobs:
#   - deployment: deploy
#     environment: test
#     pool: Hosted Ubuntu 1604
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - bash: |
#               echo "##vso[task.setvariable variable=DeviceConnectionString;issecret=true;isOutput=true]***"
#               echo "##vso[task.setvariable variable=NodeInstrumentationKey;issecret=true;isOutput=true]***"
#             name: iac
#   - deployment: container
#     environment: test
#     dependsOn: deploy
#     pool: Hosted Ubuntu 1604
#     variables:
#       NodeInstrumentationKey: $[ dependencies.deploy.outputs['iac.NodeInstrumentationKey'] ]
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - bash: printenv | sort

# trigger:
# - '*'

# stages:
# - stage: 'StageA'
#   jobs: 
#   - job: 'JobA'
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - script: echo Hello, world!
#     - script: echo $(outer)
#     - script: echo $(extreme)
#     - script: echo $(more)

