resources:
  pipelines:
  - pipeline: mypipeline
    source: resources
    trigger:
      branches:
      - master 
container:
  repositories:
  - repository: common
    type: github
    name: juliakm/learn-var
    endpoint: MyContosoServiceConnection
    trigger: 
        - master
        - release/*
  containers:
  - container: javascript
    type: ACR
    azureSubscription: ARM
    resourceGroup: cloud-shell-storage-eastus
    repository: mycontainerjulia.azurecr.io/juliakmpipelinesjavascriptdocker
    registry: mycontainerjulia.azurecr.io


steps:
- script: echo hello
- script: echo $(Build.Reason)
- script: echo $(resources.triggeringAlias)
- script: echo $(resources.triggeringCategory) 
#- script: echo $(resources.container.javascript.type)
#- script: echo $(resources.containers.container.javascript.type)
- script: printenv