trigger:
  - '*'

variables:
  b: "Hello" 

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job:
  variables:
    a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
  steps:
    - bash: echo $(a)