resources:
  containers:
  - container: mycontainer
    type: ACR
    azureSubscription: ARM
    resourceGroup: Visual Studio Enterprise - Julia
    registry: mycontainerjulia
    #repository: xxx/docker-acr:v1-tag


  steps:
    - script: echo $(resources.container.mycontainer.type)

