resources:
  containers:
  - container: javascript
    image: mycontainerjulia.azurecr.io/juliakmpipelinesjavascriptdocker
    endpoint: myServiceConnection

steps:
- script: echo hello
- script: echo $(resources.container.javascript.registry)
