resources:
  containers:
  - container: javascript
    type: ACR
    azureSubscription: ARM
    resourceGroup: cloud-shell-storage-eastus
    repository: mycontainerjulia.azurecr.io/juliakmpipelinesjavascriptdocker
    registry: mycontainerjulia.azurecr.io
  #- container: js2
    #image: mycontainerjulia.azurecr.io/juliakmpipelinesjavascriptdocker
    #endpoint: myServiceConnection


steps:
- script: echo hello
- script: echo $(resources.container.javascript.type)
- script: echo $(resources.containers.container.javascript.type)