trigger:
- '*'

stages:
- stage: 'StageA'
  jobs: 
  - job: 'JobA'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Hello, world!
    - script: echo $(outer)
    - script: echo $(extreme)

